version: '3.12'

services:
  web:
    build: .
    container_name: django_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=aircraft_db
      - DB_USER=postgres
      - DB_PASSWORD=123456789
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: aircraft_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d  # Mount backup folder

volumes:
  postgres_data:
